/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    GoldLedger: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_goldTokenAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes12",
              name: "uniqueIdentifier",
              type: "bytes12",
            },
            {
              indexed: true,
              internalType: "address",
              name: "registrar",
              type: "address",
            },
          ],
          name: "GoldRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes12",
              name: "uniqueIdentifier",
              type: "bytes12",
            },
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "date",
              type: "string",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          inputs: [],
          name: "getAllGoldDetails",
          outputs: [
            {
              components: [
                {
                  internalType: "bytes12",
                  name: "uniqueIdentifier",
                  type: "bytes12",
                },
                {
                  internalType: "string",
                  name: "weight",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "weightInGrams",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "purity",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "certificationDetails",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "certificationDate",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "mineLocation",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "parentGoldId",
                  type: "bytes12",
                },
                {
                  internalType: "bool",
                  name: "hasParentGoldId",
                  type: "bool",
                },
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  components: [
                    {
                      internalType: "address",
                      name: "owner",
                      type: "address",
                    },
                    {
                      internalType: "uint256",
                      name: "timestamp",
                      type: "uint256",
                    },
                    {
                      internalType: "string",
                      name: "date",
                      type: "string",
                    },
                  ],
                  internalType: "struct GoldLedger.OwnershipRecord[]",
                  name: "ownershipHistory",
                  type: "tuple[]",
                },
              ],
              internalType: "struct GoldLedger.GoldDetails[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          name: "getGoldByOwner",
          outputs: [
            {
              internalType: "bytes12[]",
              name: "",
              type: "bytes12[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes12",
              name: "_uniqueIdentifier",
              type: "bytes12",
            },
          ],
          name: "getGoldDetails",
          outputs: [
            {
              components: [
                {
                  internalType: "bytes12",
                  name: "uniqueIdentifier",
                  type: "bytes12",
                },
                {
                  internalType: "string",
                  name: "weight",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "weightInGrams",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "purity",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "certificationDetails",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "certificationDate",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "mineLocation",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "parentGoldId",
                  type: "bytes12",
                },
                {
                  internalType: "bool",
                  name: "hasParentGoldId",
                  type: "bool",
                },
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  components: [
                    {
                      internalType: "address",
                      name: "owner",
                      type: "address",
                    },
                    {
                      internalType: "uint256",
                      name: "timestamp",
                      type: "uint256",
                    },
                    {
                      internalType: "string",
                      name: "date",
                      type: "string",
                    },
                  ],
                  internalType: "struct GoldLedger.OwnershipRecord[]",
                  name: "ownershipHistory",
                  type: "tuple[]",
                },
              ],
              internalType: "struct GoldLedger.GoldDetails",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          name: "getTotalGoldHoldings",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "goldToken",
          outputs: [
            {
              internalType: "contract GoldToken",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_weight",
              type: "string",
            },
            {
              internalType: "string",
              name: "_purity",
              type: "string",
            },
            {
              internalType: "string",
              name: "_description",
              type: "string",
            },
            {
              internalType: "string",
              name: "_certificationDetails",
              type: "string",
            },
            {
              internalType: "string",
              name: "_certificationDate",
              type: "string",
            },
            {
              internalType: "string",
              name: "_mineLocation",
              type: "string",
            },
            {
              internalType: "bytes12",
              name: "_parentGoldId",
              type: "bytes12",
            },
          ],
          name: "registerGold",
          outputs: [
            {
              internalType: "bytes12",
              name: "",
              type: "bytes12",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalRegistrations",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes12",
              name: "_uniqueIdentifier",
              type: "bytes12",
            },
            {
              internalType: "address",
              name: "_newOwner",
              type: "address",
            },
            {
              internalType: "string",
              name: "_transferDate",
              type: "string",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    GoldToken: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "allowance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
          ],
          name: "ERC20InsufficientAllowance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
          ],
          name: "ERC20InsufficientBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "approver",
              type: "address",
            },
          ],
          name: "ERC20InvalidApprover",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
          ],
          name: "ERC20InvalidReceiver",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "ERC20InvalidSender",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
          ],
          name: "ERC20InvalidSpender",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [],
          name: "GOLD_TO_TOKEN_RATE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
          ],
          name: "allowance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "goldWeight",
              type: "uint256",
            },
          ],
          name: "burnGoldTokens",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "getGoldHoldings",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          name: "getTotalGoldHoldings",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "goldLedgerContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "goldWeight",
              type: "uint256",
            },
          ],
          name: "mintGoldTokens",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_goldLedgerAddress",
              type: "address",
            },
          ],
          name: "setGoldLedgerContract",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "transfer",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        allowance: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        approve: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        balanceOf: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        decimals: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        name: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        symbol: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        totalSupply: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        transfer: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        transferFrom: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        owner: "@openzeppelin/contracts/access/Ownable.sol",
        renounceOwnership: "@openzeppelin/contracts/access/Ownable.sol",
        transferOwnership: "@openzeppelin/contracts/access/Ownable.sol",
      },
    },
  },
  84532: {
    GoldLedger: {
      address: "0xc2591EcC12DB13eef1191459A00e14f6f9850345",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "uniqueIdentifier",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "registrar",
              type: "address",
            },
          ],
          name: "GoldRegistered",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_uniqueIdentifier",
              type: "uint256",
            },
          ],
          name: "getGoldDetails",
          outputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "weight",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "purity",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "certificationDetails",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "certificationDate",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "mineLocation",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "parentGoldId",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "uniqueIdentifier",
                  type: "uint256",
                },
              ],
              internalType: "struct GoldLedger.GoldDetails",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "goldRegistry",
          outputs: [
            {
              internalType: "string",
              name: "weight",
              type: "string",
            },
            {
              internalType: "string",
              name: "purity",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "certificationDetails",
              type: "string",
            },
            {
              internalType: "string",
              name: "certificationDate",
              type: "string",
            },
            {
              internalType: "string",
              name: "mineLocation",
              type: "string",
            },
            {
              internalType: "string",
              name: "parentGoldId",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "uniqueIdentifier",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_weight",
              type: "string",
            },
            {
              internalType: "string",
              name: "_purity",
              type: "string",
            },
            {
              internalType: "string",
              name: "_description",
              type: "string",
            },
            {
              internalType: "string",
              name: "_certificationDetails",
              type: "string",
            },
            {
              internalType: "string",
              name: "_certificationDate",
              type: "string",
            },
            {
              internalType: "string",
              name: "_mineLocation",
              type: "string",
            },
            {
              internalType: "string",
              name: "_parentGoldId",
              type: "string",
            },
          ],
          name: "registerGold",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalRegistrations",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
  11155111: {},
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
